# Generated by Django 4.2.5 on 2023-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imap_server",
                    models.CharField(max_length=50, verbose_name="Адрес IMAP сервера"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Адрес проверяемой почты"
                    ),
                ),
                (
                    "email_key",
                    models.CharField(
                        max_length=30, verbose_name="Ключ к почтовому ящику"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="Название задания"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание задания"
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=300, verbose_name="Тема письма"),
                ),
                (
                    "sender",
                    models.CharField(max_length=100, verbose_name="Отправитель"),
                ),
                (
                    "search_string",
                    models.TextField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Поисковый запрос IMAP",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("interval", "Интервал"), ("cron", "Кастомный")],
                        default="interval",
                        max_length=20,
                        verbose_name="Триггер",
                    ),
                ),
                (
                    "interval",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Периодичность"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Год (YYYY)",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Месяц (1-12)",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="День (1-31)",
                    ),
                ),
                (
                    "week",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Неделя ISO (1-53)",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="День недели (0-6; 0=понедельник)",
                    ),
                ),
                (
                    "hour",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Часы (0-23)",
                    ),
                ),
                (
                    "minutes",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Минуты (0-59)",
                    ),
                ),
                (
                    "seconds",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Секунды (0-59)",
                    ),
                ),
                (
                    "sec_interval",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Интервал в секундах"
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        verbose_name="Идентификатор задачи",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Остановлено"), (1, "Активно")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
            ],
        ),
    ]
